site_name: Cadwork Math Utilities

repo_name: cwapi3d/cwmath
repo_url: https://github.com/cwapi3d/cwmath
edit_uri: ""

copyright: Copyright &copy; 2022 Cadwork

site_url: https://python.cadwork.dev/

theme:
    name: material
    logo: cw_logo.svg 
    favicon: cw_logo.svg 
    version: V29
    palette:
    - scheme: slate
      primary: "light-blue"
      accent: "pink"
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    - scheme: default
      primary: "light-blue"
      accent: "pink"
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    features:
    - search.suggest
    - search.highlight
    - navigation.tabs
    - toc.integrate

nav:
  - Home: index.md
  - Getting Started:
    - Geometry: geometry.md
    - Contributing: contributing.md
    - Style Guide: style_guide.md
  - Reference:
    - functions.md

markdown_extensions:
  - attr_list  
  - admonition
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.highlight:
      linenums: true
      linenums_style: pymdownx-inline
  - pymdownx.superfences:
  - footnotes:
      SEPARATOR: _footnote_
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: cwapi3d
      repo: cwmath

extra_css:
  - stylesheets/extra.css

plugins:
  - search:
      separator: '[\s\-\.\_]+'
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          options:
            show_source: false
          setup_commands:
            - import sys
            - from unittest.mock import MagicMock as mock
            - sys.modules["cadwork"] = mock()

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/cwapi3d/cwmath
      name: cwmath
