site_name: Cadwork Math Utilities

repo_name: cwapi3d/cwmath
repo_url: https://github.com/cwapi3d/cwmath

copyright: Copyright 2024 Cadwork

site_url: https://python.cadwork.dev/

theme:
  name: material
  logo: cw_logo.svg
  favicon: cw_logo.svg
  version: V30
  #    palette:
  #    - scheme: slate
  #      primary: "light-blue"
  #      accent: "pink"
  #      toggle:
  #        icon: material/brightness-4
  #        name: Switch to light mode
  #    - scheme: default
  #      primary: "light-blue"
  #      accent: "pink"
  #      toggle:
  #        icon: material/brightness-7
  #        name: Switch to dark mode
  features:
    - search.suggest
    - search.highlight
    - navigation.tabs
    - content.code.copy
    - toc.integrate

nav:
  - Home: index.md
  - Getting Started:
      - Geometry: geometry.md
      - Contributing: contributing.md
      - Style Guide: style_guide.md
  - Reference:
      - functions.md
      - vector3d.md
      - plane3d.md

markdown_extensions:
  - md_in_html
  - attr_list
  - admonition
  #  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.highlight:
      linenums: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - footnotes:
  - pymdownx.emoji:
      emoji_index: !!python/name:pymdownx.emoji.gemoji
      emoji_generator: !!python/name:pymdownx.emoji.to_alt

        #extra_css:
        #  - stylesheets/extra.css

plugins:
  - search
  - mkdocstrings
  #      handlers:
  #        python:
  #          paths: [src]
  #          options:
  #            show_source: false
  #          setup_commands:
  #            - import sys
  #            - from unittest.mock import MagicMock as mock
  #            - sys.modules["cadwork"] = mock()
  - privacy

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/cwapi3d
      name: cwapi3d
