# Repository
repo_name: cwapi3d/cwmath
repo_url: https://github.com/cwapi3d/cwmath
edit_uri: ""

# Copyright
copyright: Copyright &copy; 2021-2022 cadwork 

site_name: Cadwork Math Utilities
site_url: https://python.cadwork.dev/
theme:
    name: material
    nav_style: dark
    logo: cw_logo.svg 
    favicon: cw_logo.svg 
    version: v29
    palette:
      - media: "(prefers-color-scheme: light)"
        scheme: default
        toggle:
          name: Switch to light mode
          icon: material/weather-sunny
      - media: "(prefers-color-scheme: dark)"
        scheme: slate
        primary: grey
        accent: blue
        toggle:
          name: Switch to dark mode
          icon: material/weather-night 
    features:
    - search.suggest
    - search.highlight
    - navigation.instant
nav:
  - Cadwork math: index.md
  - Contribution: Documentation/contributing.md
  - Geometry: geometry.md
  - Style Guide: style_guide.md
  - Documentation:
    - Functions: Documentation/functions.md
  

markdown_extensions:
  - attr_list  
  - admonition
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.highlight:
  - pymdownx.superfences:
  - footnotes:
      SEPARATOR: _footnote_
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: cwapi3d
      repo: cwmath
extra_css:
  - stylesheets/extra.css
plugins:
  - search:
      separator: '[\s\-\.\_]+'     
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          setup_commands:
                      - import sys
          rendering:
            show_source: false                 
extra:
  generator: false
  copyright: Copyright &copy; 2021 cadwork
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/cwapi3d/cwmath
      name: cwmath
