[project]
name = "cwmath"
version = "1.0.1"

authors = [{ name = "Cadwork", email = "it@cadwork.ca" }]
requires-python = ">=3.14"
description = "Cadwork Math Utilities"
readme = "README.md"
license-files = [ "LICENSE" ]
keywords = [ "cadwork" ]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Environment :: Plugins",
    "Intended Audience :: Developers",
    "Operating System :: Microsoft :: Windows",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.14",
    "Topic :: Software Development :: Libraries",
]

[project.urls]
Homepage = "https://github.com/cwapi3d/cwmath"

[dependency-groups]
dev = [
    "black>=26.5.1",
    "mkdocs>=1.6.1",
    "mkdocs-autorefs>=1.4.4",
    "mkdocs-material>=9.7.7",
    "mkdocstrings[python]>=1.0.6",
    "pre-commit>=4.6.2",
    "pytest>=9.1.1",
    "pytest-cov>=7.1.0",
    "ruff>=0.16.3",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
