name: Publish CwMath Package

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'setup.py'

jobs:
  build-and-publish:
    name: Build and Publish
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - run: >-
          python -m
          pip install
          build
          --user
      - run: >-
          python -m
          build
          --sdist
          --wheel
          --outdir dist/
          .
      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
